export const GET_SALE_ITEMS = 'GET_SALE_ITEMS';
export const GET_SALE_ITEM_DETAIL = 'GET_SALE_ITEM_DETAIL';
export const SORT_SALE_ITEMS = 'SORT_SALE_ITEMS';
export const SORT_REQUEST_ITEMS = 'SORT_REQUEST_ITEMS';
export const GET_CATEGORIES = 'GET_CATEGORIES' 
export const GET_PAYMENT = 'GET_PAYMENT' 
export const GET_USER = 'GET_USER' 
export const GET_REQUEST_ITEMS = 'GET_REQUEST_ITEMS';
export const GET_REQUEST_ITEM_DETAIL = 'GET_REQUEST_ITEM_DETAIL';
export const SET_ITEM_TYPE = 'SET_ITEM_TYPE'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_SUB_CATEGORY = 'SET_SUB_CATEGORY'
export const SET_REQUEST_FORM = 'SET_REQUEST_FORM'
export const SET_SALE_FORM = 'SET_SALE_FORM'
export const ADD_REQUEST_PRODUCT = 'ADD_REQUEST_PRODUCT'
export const ADD_SALE_PRODUCT = 'ADD_SALE_PRODUCT'
 
